language: cpp
compiler: gcc
sudo: required
dist: trusty

group: deprecated-2017Q3

addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - python
   # - libsdl1.2-dev
   # - libsdl-image1.2-dev
   # - libgtkmm-2.4-dev
   # - g++-4.8
   # - libzmqpp-dev
   # - texlive-latex-base
   # - texlive-fonts-recommended

before_install:
 - pip install --upgrade pip wheel
 - pip install jinja2 lxml numpy
 - pip install scons==2.5.1
 - pip install pyx==0.12.1
 - pip3 install jinja2
 - pip3 install lxml
 - pip3 install numpy
 - pip3 install scons
 - pip3 install  pyx

cache:
 directories:
  - $HOME/cache


script: echo "Script!"

jobs:
  include:
    - stage: deploy
      script:
        - "python3 tools/authors.py --handles --count --shoutout --since 2017-01-01"
        - "python3 tools/system_design/builder/system_layout.py examples/communication/xml/communication.xml -o /tmp"
      env: TEST_SUITE=""
